#!/usr/bin/env bash
# Tests for the Codex/.agents skills mirror generated by bin/build-codex-skills.py.
# Verifies: skills are in sync with commands/, each has name+description frontmatter,
# no unresolved ${CLAUDE_PLUGIN_ROOT}, and AGENTS.md fits Codex's 32 KiB doc cap.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0; FAIL=0
ok(){ echo "PASS: $1"; PASS=$((PASS+1)); }
no(){ echo "FAIL: $1"; FAIL=$((FAIL+1)); }

# 1. Generated skills are in sync with commands/ (regeneration is a no-op).
if python3 "$ROOT/bin/build-codex-skills.py" --check >/dev/null 2>&1; then ok "skills in sync with commands/"; else no "skills OUT OF SYNC — run bin/build-codex-skills.py"; fi

# 2. One skill per command + reference doc, each with name + description frontmatter.
srcs=$(( $(ls "$ROOT/commands"/*.md | wc -l) + $(ls "$ROOT/reference"/*.md | wc -l) ))
skills=$(ls -d "$ROOT/.agents/skills"/*/ 2>/dev/null | wc -l | tr -d ' ')
[ "$srcs" = "$skills" ] && ok "one skill per command/reference ($skills)" || no "source/skill count mismatch ($srcs vs $skills)"
miss=0
for s in "$ROOT/.agents/skills"/*/SKILL.md; do
  head -4 "$s" | grep -q "^name: " && head -4 "$s" | grep -q "^description: " || { miss=$((miss+1)); echo "  missing frontmatter: $s"; }
done
[ "$miss" = "0" ] && ok "every SKILL.md has name+description" || no "$miss skills missing frontmatter"

# 3. No unresolved plugin-root tokens leaked into the skills.
if grep -rq "CLAUDE_PLUGIN_ROOT" "$ROOT/.agents/skills"/; then no "CLAUDE_PLUGIN_ROOT leaked into skills"; else ok "no CLAUDE_PLUGIN_ROOT in skills"; fi

# 4. AGENTS.md is under Codex's 32 KiB project_doc_max_bytes default.
bytes=$(wc -c < "$ROOT/AGENTS.md" | tr -d ' ')
[ "$bytes" -lt 32768 ] && ok "AGENTS.md ${bytes}B < 32 KiB" || no "AGENTS.md ${bytes}B exceeds 32 KiB cap"

echo "----"; echo "$PASS passed, $FAIL failed"; [ "$FAIL" -eq 0 ]
